---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Lisseth Gonzalez"
pagetitle: "L01 Lisseth Gonzalez"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[My Github Link](https://github.com/stat301-3-2026-spring/l01-review-lissethg0610)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

- Data cleaning 
- Exploratory Data Analysis (EDA)
- Initial splitting 
- Create folds 
- Make recipes/feature engineering 
- Set workflows 
- Fit/tune models 
- Assess best model 
- Select best model
- Fit/train best model 
- Assess best model 

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning refers to task driven machine learning using pre-categorized data, such as classification and regression. Unsupervised learning refers to data driven machine learning that relies on pattern recognition, including clustering and association. 

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

A descriptive models purpose is to illustrate and describe data, often using visual tools to show trends or relationships. 

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

An inferential model intends to produce a result to test a hypothesis related to a research question. This model type relies on the assumption in the hypothesis. 

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

A predictive model is used to produce a prediction on existing data, which can be implemented to predict new data. 

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model forms predictions based on an equation that estimates the parameters of the model. This model type creates an f(x) equation that is used to predict new data. 

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

An empirical model does not form predictions based on an equation. This model type tends to have higher accuracy, although it requires more data to observe the patterns. 

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

A mechanistic model is synonymous to a parametric model, while an empirically driven model is synonymous to a nonparametric model. 

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

A mechanistic model is easier to interpret since the parameters are defined by the produced equation, therefore the results can be explained by a formula. 

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

An empirically driven model is the more flexible model, since it is based on data points rather than an equation. For example, a simple line of best fit cannot capture potential polynomial or curved patterns. 

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

For a mechanistic model there is a high risk for underfitting, making it a high bias-low variance model. For an empirically driven model there is a high risk for overfitting, making it a low bias-high variance model. 

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

A regression machine learning problem uses the values in the data to predict a continuous numerical value. A classification machine learning problem uses the values in the data to predict a categorical outcome or class label, rather than a continuous numerical value.

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying keeps the same proportion of each outcome in every split. This makes sure the training and test data look similar, so the model learns and is evaluated fairly.

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

In v-fold cross validation with repeats, the data is split into v equal parts (folds). The model is trained on v−1 folds and tested on the remaining fold, repeating this process until every fold has been used as the test set. It is used to produce stable estimate of model performance by reducing the impact of how the data is split.

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrap resampling is used when the dataset is small or we want to make the most of limited data. Bootstrapping repeatedly samples with replacement from the data, allowing us to create the prediction while using most observations for training each time. It can give a more flexible estimate of variability and uncertainty in model performance compared to v-fold cross validation.

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning is the process of adjusting a model’s hyperparameters to find the best-performing version of the model. Tuning expands beyond the default settings for each models parameters to improve performance. 

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

Common performance metrics for regression include: 

- RMSE (Root Mean Squared Error)
- MAE (Mean Absolute Error)

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Common performance metrics for classification include: 

- Accuracy 
- ROC-AUC

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Inferential: The question is about understanding the impact of service calls on churn. The goal is to draw conclusions or explain patterns in the data, not just predict outcomes. This question type requires forming a hypothesis, making it an inferential problem. 

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Prediction: This question focuses on estimating the whether or not that a customer will churn. The goal is to make an accurate classification prediction based on existing data. 

:::

